// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: migrations.sql

package dal

import (
	"context"
)

const getLastMigrationVersion = `-- name: GetLastMigrationVersion :one
SELECT version
FROM schema_migrations
ORDER BY version DESC
LIMIT 1
`

func (q *Queries) GetLastMigrationVersion(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, getLastMigrationVersion)
	var version int64
	err := row.Scan(&version)
	return version, err
}
